name: Node.js CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install dependencies
        working-directory: ./node/express-prisma-typescript
        run: npm install
      - name: Run tests
        working-directory: ./node/express-prisma-typescript
        run: npm run test
