name: Twitter backend challenge action

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Change working directory
        run: cd node/express-prisma-typescript
      - run: npm install
        working-directory: node/express-prisma-typescript
      - run: npm test
        working-directory: node/express-prisma-typescript
